# Generated by Django 4.2.7 on 2023-11-26 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_filter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filter',
            name='name',
            field=models.TextField(),
        ),
    ]
